"""
scenario_reduction.py
=====================

Backward scenario reduction for the UAM stochastic model.

Input:
    scenarios generated by scenario_generator.py

Each scenario contains:

    passenger_demand:
        {(period,destination): passengers}

    aircraft:
        [
          Aircraft(
             id,
             arrival_time,
             initial_soc
          )
        ]


Output:
    reduced representative scenarios

Used before stochastic MILP optimization.
"""


import numpy as np

from .config import (
    TARGET_SCENARIOS,
    CVaR_ALPHA,
    SOC_REQUIRED,
    EVTOL_CAPACITY
)



# ============================================================
# 1. Build scenario feature vectors
# ============================================================


def build_feature_vectors(scenarios):

    """
    Convert each scenario into numerical vector.

    Features:

    1. Passenger demand trajectory
    2. Aircraft arrival trajectory
    3. Charging stress
    """


    if len(scenarios) == 0:
        return scenarios


    destinations = sorted(
        {
            destination

            for s in scenarios

            for (_, destination)
            in s.passenger_demand.keys()
        }
    )


    raw_vectors=[]


    for s in scenarios:


        features=[]


        # ---------------------------
        # Passenger demand
        # ---------------------------

        periods = sorted(
            {
                t

                for (t,d)
                in s.passenger_demand.keys()
            }
        )


        for t in periods:

            for d in destinations:

                features.append(
                    s.passenger_demand.get(
                        (t,d),
                        0
                    )
                )


        # ---------------------------
        # Aircraft arrivals
        # ---------------------------

        arrival_vector = np.zeros(
            len(periods)
        )


        for aircraft in s.aircraft:


            period = (
                aircraft.arrival_time
                -
                periods[0]
            )


            if period in periods:

                idx = periods.index(period)

                arrival_vector[idx]+=1



        features.extend(
            arrival_vector
        )


        # ---------------------------
        # Charging stress
        # ---------------------------

        workload=np.zeros(
            len(periods)
        )


        for aircraft in s.aircraft:


            deficit=max(
                0,
                SOC_REQUIRED -
                aircraft.initial_soc
            )


            idx=min(
                len(periods)-1,
                max(
                    0,
                    int(
                    (
                    aircraft.arrival_time-
                    periods[0]
                    ) /
                    15
                    )
                )
            )


            workload[idx]+=deficit



        features.extend(
            workload
        )


        raw_vectors.append(
            np.array(features)
        )


    matrix=np.vstack(
        raw_vectors
    )


    std=matrix.std(axis=0)

    std[
        std<1e-9
    ]=1


    normalized=(

        matrix-
        matrix.mean(axis=0)

    )/std



    for s,v in zip(
        scenarios,
        normalized
    ):

        s.feature_vector=v



    return scenarios



# ============================================================
# 2. Distance matrix
# ============================================================


def compute_distance_matrix(
        scenarios
):


    n=len(scenarios)


    dist=np.zeros(
        (n,n)
    )


    for i in range(n):

        for j in range(i+1,n):


            d=np.linalg.norm(

                scenarios[i].feature_vector
                -
                scenarios[j].feature_vector

            )


            dist[i,j]=d

            dist[j,i]=d



    return dist



# ============================================================
# 3. Backward reduction
# ============================================================


def backward_reduce(
        scenarios,
        target_size
):


    scenarios=list(
        scenarios
    )


    n=len(scenarios)


    probability=1/n


    for s in scenarios:

        s.probability=probability



    while len(scenarios)>target_size:


        dist=compute_distance_matrix(
            scenarios
        )


        remove=None

        closest=None

        minimum=float("inf")


        for i,s in enumerate(scenarios):


            distances=[

                dist[i,j]

                for j in range(len(scenarios))

                if i!=j

            ]


            nearest=min(
                distances
            )


            cost=(
                s.probability
                *
                nearest
            )


            if cost<minimum:

                minimum=cost

                remove=i


                candidates=[
                    j
                    for j in range(
                        len(scenarios)
                    )
                    if j!=i
                ]


                closest=min(

                    candidates,

                    key=lambda j:
                    dist[i,j]

                )


        scenarios[closest].probability += (
            scenarios[remove].probability
        )


        scenarios.pop(
            remove
        )


    return scenarios



# ============================================================
# 4. Stress preservation
# ============================================================


def calculate_stress_score(
        scenario
):

    """

    High stress:

    - high passenger demand
    - few aircraft
    - low SoC

    """


    passengers=sum(
        scenario.passenger_demand.values()
    )


    aircraft=len(
        scenario.aircraft
    )


    charging_workload=sum(

        max(
            0,
            SOC_REQUIRED-
            a.initial_soc
        )

        for a in scenario.aircraft

    )


    return (

        passengers

        -
        EVTOL_CAPACITY*aircraft

        +
        0.05*charging_workload

    )



# ============================================================
# 5. Main function
# ============================================================


def reduce_scenarios(
        scenarios,
        target_size=TARGET_SCENARIOS
):


    scenarios=build_feature_vectors(
        scenarios
    )


    for s in scenarios:

        s.stress_score=calculate_stress_score(
            s
        )


    reduced=backward_reduce(

        scenarios,

        target_size

    )


    total=sum(
        s.probability
        for s in reduced
    )


    for s in reduced:

        s.probability/=total



    return reduced